### ISSUE TITLE
Adapt to Godot 3

### ISSUE THREAD

**Issue by eberfreitas** [arypbatista/godot-swipe-detector#17]
Some of the API has changed. I can help maybe I guess. Let me know!

**Comment by arypbatista** [comment]
Hi! Yeah, I had this in mind since they released 3.0. I would be great if you can migrate the code to use 3.0 API. Just create a pull request when you are ready. Let me know if you need some help!

**Comment by StraToN** [comment]
Started #18  :)

**Comment by arypbatista** [comment]
Solved by #18
